[package]
name = "rs-telex"
version = "0.1.0"
edition = "2024"
authors = ["duyphan0503 <https://github.com/duyphan0503>"]
repository = "https://github.com/duyphan0503/rs-telex"
license = "MIT"

[dependencies]
rs-telex-sys = { path = "../rs-telex-sys" }
serde = { version = "1.0", features = ["derive"] }
zbus = { version = "5.19.0", features = ["blocking-api"] }
zvariant = "5.15"
